name: Build AppInsight APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip AppInsightTracker.zip -d project

      - name: Change directory into project
        working-directory: project
        run: ls -R .

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Gradle execution
        run: chmod +x project/gradlew

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project/app/build/outputs/apk/debug/*.apk
